# Generated by Django 5.1.4 on 2025-05-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='path/to/upload/')),
                ('description', models.TextField()),
                ('facility', models.TextField()),
                ('location', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aura.category')),
            ],
        ),
    ]
