# Generated by Django 5.1.4 on 2025-05-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aura', '0002_venue_venueimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='venue',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
