# Generated by Django 5.1.4 on 2025-05-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aura', '0003_remove_product_category_remove_venueimage_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aura.event'),
        ),
    ]
