# Generated by Django 5.1.4 on 2025-05-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aura', '0007_booking_bookingfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingfood',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
